# Generated by Django 3.2.25 on 2024-06-24 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='assignedNurseName',
            field=models.CharField(default='Unknown Nurse', max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('department', 'department'), ('general consultation', 'general consultation'), ('Pediatrician', 'Pediatrician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Psychiatrist', 'Psychiatrist'), ('Obstetrician/Gynecologist', 'Obstetrician/Gynecologist'), ('OB/GYN', 'OB/GYN'), ('Ophthalmologist', 'Ophthalmologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Otolaryngologist', 'Otolaryngologist'), ('ENT Specialist', 'ENT Specialist'), ('Pathologist', 'Pathologist'), ('Radiologist', 'Radiologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Emergency Medicine Physician', 'Emergency Medicine Physician'), ('Gastroenterologist', 'Gastroenterologist'), ('Hematologist', 'Hematologist'), ('Nephrologist', 'Nephrologist'), ('Oncologist', 'Oncologist'), ('Pulmonologist', 'Pulmonologist'), ('Rheumatologist', 'Rheumatologist'), ('Urologist', 'Urologist'), ('Endocrinologist', 'Endocrinologist'), ('Infectious Disease Specialist', 'Infectious Disease Specialist'), ('Allergist/Immunologist', 'Allergist/Immunologist'), ('Surgeon', 'Surgeon'), ('General Surgeon', 'General Surgeon'), ('Cardiothoracic Surgeon', 'Cardiothoracic Surgeon'), ('Plastic Surgeon', 'Plastic Surgeon'), ('Neonatologist', 'Neonatologist'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists')], default='department', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/NurseProfilePic/')),
                ('department', models.CharField(choices=[('department', 'department'), ('general consultation', 'general consultation'), ('Pediatrician', 'Pediatrician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Psychiatrist', 'Psychiatrist'), ('Obstetrician/Gynecologist', 'Obstetrician/Gynecologist'), ('OB/GYN', 'OB/GYN'), ('Ophthalmologist', 'Ophthalmologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Otolaryngologist', 'Otolaryngologist'), ('ENT Specialist', 'ENT Specialist'), ('Pathologist', 'Pathologist'), ('Radiologist', 'Radiologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Emergency Medicine Physician', 'Emergency Medicine Physician'), ('Gastroenterologist', 'Gastroenterologist'), ('Hematologist', 'Hematologist'), ('Nephrologist', 'Nephrologist'), ('Oncologist', 'Oncologist'), ('Pulmonologist', 'Pulmonologist'), ('Rheumatologist', 'Rheumatologist'), ('Urologist', 'Urologist'), ('Endocrinologist', 'Endocrinologist'), ('Infectious Disease Specialist', 'Infectious Disease Specialist'), ('Allergist/Immunologist', 'Allergist/Immunologist'), ('Surgeon', 'Surgeon'), ('General Surgeon', 'General Surgeon'), ('Cardiothoracic Surgeon', 'Cardiothoracic Surgeon'), ('Plastic Surgeon', 'Plastic Surgeon'), ('Neonatologist', 'Neonatologist'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists')], default='department', max_length=50)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
