# Generated by Django 3.2.25 on 2024-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20240624_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='assignedNurseName',
            field=models.CharField(max_length=40),
        ),
    ]
